src/Entity/Attendance.php
<?php

namespace App\Entity;

use App\Repository\AttendanceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AttendanceRepository::class)
 */
class Attendance
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $mark;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=Subject::class)
     */
    private $Subject;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMark(): ?int
    {
        return $this->mark;
    }

    public function setMark(int $mark): self
    {
        $this->mark = $mark;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(): self
    {
        $this->date = new \DateTime("now");

        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->Subject;
    }

    public function setSubject(?Subject $Subject): self
    {
        $this->Subject = $Subject;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Controller/AttendanceController.php
<?php

namespace App\Controller;

use App\Entity\Attendance;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class AttendanceController extends AbstractController
{
    private $attendance;

    public function __construct(ManagerRegistry $doctrine) {
        $this->attendance = $doctrine->getRepository(Attendance::class);
    }

    /**
     * @Route("/attendance", name="app_attendance_student")
     */
    public function index(): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        $id = $this->getUser()->getId();
        $attendance = $this->attendance->findBy(['User' => $id]);

        return $this->render('attendance/index.html.twig', [
            'attendance' => $attendance
        ]);
    }
}

templates/attendance/index.html.twig
{% extends 'panel.html.twig' %}

{% block title %}Obecność{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<main>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Data</th>
      <th scope="col">Przedmiot</th>
      <th scope="col">Obecność</th>
    </tr>
  </thead>
  <tbody>
  {% for a in attendance %}
    <tr>
      <th scope="row">{{ a.date|date('Y-m-d') }}</th>
      <td>{{ a.subject }}</td>
      {% if a.mark == 1 %}
      <td style="width: 72%;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;X</td>
      {% endif %}
      {% if a.mark == 0 %}
      <td style="width: 72%;"></td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
</main>
{% endblock %}